### ISSUE TITLE
trường hợp api vừa có get và post ?

### ISSUE THREAD

**Issue by ntvsp** [phamdinhduc795397/flutter-getx-clean-architecture#3]
trong trường hợp ArticleAPI vừa có get và vừa có post thì không biết cái này mình triển khai ntn ạ
![Screen Shot 2022-11-24 at 10 32 59](https://user-images.githubusercontent.com/66931285/203688059-f011a4a9-d39a-4983-b2e9-2990ae462a8c.png)

**Comment by phamdinhduc795397** [comment]
<img width="333" alt="Screenshot 2022-11-24 at 10 35 44" src="https://user-images.githubusercontent.com/13247813/203688362-b6b24123-435c-4e05-a5f9-6eee729b24a7.png">
Bạn dùng switch type tại `method` tương tự như `path`, return http method tương ứng nha.
